# Generated by Django 3.0.7 on 2020-07-14 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthdate', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=1000, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('user_email', models.CharField(max_length=100)),
                ('is_social_user', models.CharField(max_length=100)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Gender')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
