# Generated by Django 3.0.7 on 2020-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='phone_number',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
