# Generated by Django 3.0.7 on 2020-07-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200708_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_social_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
