# Generated by Django 3.0.8 on 2020-07-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_series',
            new_name='series',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
    ]
