# Generated by Django 3.0.7 on 2020-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_main_img',
            field=models.BooleanField(default=False),
        ),
    ]
