# Generated by Django 3.0.7 on 2020-07-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
